version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - ${COMPOSE_PHP_PORT}
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USERNAME}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_DATABASE}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${COMPOSE_DB_PORTS}
    expose:
      # Opens port 3306 on the container
      - ${COMPOSE_DB_EXPOSE}
      # Where our data will be persisted
    volumes:
      - ../test_db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: pma

    links:
      - db
    ports:
      - ${COMPOSE_PHPMYADMIN_PORT}
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_DATABASE}
    restart: always
